### PR TITLE
Added button availability and area recording buttons

### PR DESCRIPTION
**Pull request by prigorus**
I have added all buttons that are available for are recording in the native web app. Availability is also added for all buttons so that they are only possible to click when the option is available. 

I am not using a prefix so it would help for someone to check if this works okay. I am also not sure about the emergency button availability if it needs to be inverted or not.

### CODE REVIEW

**Comment by vermut** [comment]
I liked the ability to press any button at any time, because I don't trust internal OM logic. But let me attempt to make this a beta release and see how it will sit with others.

**Comment by prigorus** [comment]
> I liked the ability to press any button at any time, because I don't trust internal OM logic. But let me attempt to make this a beta release and see how it will sit with others.

For skipping areas, it's not really an issue if it's available. Although skip path is currently unavailable until that is fixed in ROS (which is in some way useful to show that it doesn't work). I like the availability for area recording since I can see that a command was accepted. I use only HA for area recording since it's more reliable than the native app when it disconnects (but I am only pushing the mower rather than driving it).

**Comment by vermut** [comment]
People report buttons not working completely

image

**Comment by PeterLinuxOSS** [comment]
> People report buttons not working completely
> 
> image

This problem was resolved in:
[fix: Button availability and area recording buttons](https://github.com/vermut/ha_openmower/pull/8/commits/573def1bbd01ec78a6d7c322b20daa3bb8ee19b6)

**Pull request merged**
